<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsAspireSharedProject>true</IsAspireSharedProject>
		<AssemblyName>GhostfolioSidekick.$(MSBuildProjectName)</AssemblyName>
		<RootNamespace>GhostfolioSidekick.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<SonarQubeSetting Include="sonar.exclusions">
			<Value>**/*.js</Value>
		</SonarQubeSetting>
		<SonarQubeSetting Include="sonar.coverage.exclusions">
			<Value>**</Value>
		</SonarQubeSetting>
	</ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />

		<PackageReference Include="Microsoft.Extensions.Http.Resilience" />
		<PackageReference Include="Microsoft.Extensions.ServiceDiscovery" />
		<PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
		<PackageReference Include="OpenTelemetry.Extensions.Hosting" />
		<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
		<PackageReference Include="OpenTelemetry.Instrumentation.Http" />
		<PackageReference Include="OpenTelemetry.Instrumentation.Runtime" />
	</ItemGroup>

</Project>
