<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AssemblyName>GhostfolioSidekick.$(MSBuildProjectName)</AssemblyName>
		<RootNamespace>GhostfolioSidekick.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
	</PropertyGroup>

	<PropertyGroup>
		<TreatWarningsAsErrors>True</TreatWarningsAsErrors>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="FuzzySharp" />
		<PackageReference Include="Microsoft.Bcl.TimeProvider" />
		<PackageReference Include="Microsoft.Extensions.Caching.Memory" />
		<PackageReference Include="Microsoft.Extensions.Logging" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
		<PackageReference Include="Newtonsoft.Json" />
		<PackageReference Include="Polly" />
		<PackageReference Include="RestSharp" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Configuration\Configuration.csproj" />
		<ProjectReference Include="..\Cryptocurrency\Cryptocurrency.csproj" />
		<ProjectReference Include="..\ExternalDataProvider\ExternalDataProvider.csproj" />
		<ProjectReference Include="..\Model\Model.csproj" />
		<ProjectReference Include="..\Parsers\Parsers.csproj" />
	</ItemGroup>

</Project>
