// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Major Code Smell", "S2629:Logging templates should be constant", Justification = "<Pending>", Scope = "member", Target = "~M:GhostfolioSidekick.GhostfolioAPI.Strategies.ApiStrategyBase.GetUnitPrice(GhostfolioSidekick.Model.Symbols.SymbolProfile,System.DateTime)~System.Threading.Tasks.Task{GhostfolioSidekick.Model.Money}")]
[assembly: SuppressMessage("Major Code Smell", "S2629:Logging templates should be constant", Justification = "<Pending>", Scope = "member", Target = "~M:GhostfolioSidekick.GhostfolioAPI.API.MarketDataService.UpdateKnownIdentifiers(GhostfolioSidekick.Model.Symbols.SymbolProfile,System.String[])~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Major Code Smell", "S2629:Logging templates should be constant", Justification = "<Pending>", Scope = "member", Target = "~M:GhostfolioSidekick.GhostfolioAPI.API.MarketDataService.CreateSymbol(GhostfolioSidekick.Model.Symbols.SymbolProfile)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Major Code Smell", "S2629:Logging templates should be constant", Justification = "<Pending>", Scope = "member", Target = "~M:GhostfolioSidekick.GhostfolioAPI.API.MarketDataService.FindSymbolByIdentifier(System.String[],GhostfolioSidekick.Model.Currency,GhostfolioSidekick.Model.Activities.AssetClass[],GhostfolioSidekick.Model.Activities.AssetSubClass[],System.Boolean,System.Boolean)~System.Threading.Tasks.Task{GhostfolioSidekick.Model.Symbols.SymbolProfile}")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "<Pending>", Scope = "member", Target = "~M:GhostfolioSidekick.GhostfolioAPI.API.MarketDataService.FindSymbolByIdentifier(System.String[],GhostfolioSidekick.Model.Currency,GhostfolioSidekick.Model.Activities.AssetClass[],GhostfolioSidekick.Model.Activities.AssetSubClass[],System.Boolean,System.Boolean)~System.Threading.Tasks.Task{GhostfolioSidekick.Model.Symbols.SymbolProfile}")]
[assembly: SuppressMessage("Major Code Smell", "S2629:Logging templates should be constant", Justification = "<Pending>", Scope = "member", Target = "~M:GhostfolioSidekick.GhostfolioAPI.API.MarketDataService.UpdateSymbol(GhostfolioSidekick.Model.Symbols.SymbolProfile)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "<Pending>", Scope = "member", Target = "~M:GhostfolioSidekick.GhostfolioAPI.API.MarketDataService.UpdateSymbol(GhostfolioSidekick.Model.Symbols.SymbolProfile)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Major Code Smell", "S2629:Logging templates should be constant", Justification = "<Pending>", Scope = "member", Target = "~M:GhostfolioSidekick.GhostfolioAPI.API.MarketDataService.DeleteSymbol(GhostfolioSidekick.Model.Symbols.SymbolProfile)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Major Code Smell", "S2629:Logging templates should be constant", Justification = "<Pending>", Scope = "member", Target = "~M:GhostfolioSidekick.GhostfolioAPI.API.MarketDataService.SetMarketPrice(GhostfolioSidekick.Model.Symbols.SymbolProfile,GhostfolioSidekick.Model.Money,System.DateTime)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Major Code Smell", "S2629:Logging templates should be constant", Justification = "<Pending>", Scope = "member", Target = "~M:GhostfolioSidekick.GhostfolioAPI.API.MarketDataService.SetSymbolAsBenchmark(GhostfolioSidekick.Model.Symbols.SymbolProfile)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "<Pending>", Scope = "member", Target = "~M:GhostfolioSidekick.GhostfolioAPI.API.MarketDataService.SetSymbolAsBenchmark(GhostfolioSidekick.Model.Symbols.SymbolProfile)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Major Code Smell", "S2629:Logging templates should be constant", Justification = "<Pending>", Scope = "member", Target = "~M:GhostfolioSidekick.GhostfolioAPI.API.MarketDataService.GatherAllMarktData~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Major Code Smell", "S2629:Logging templates should be constant", Justification = "<Pending>", Scope = "member", Target = "~M:GhostfolioSidekick.GhostfolioAPI.API.ExchangeRateService.GetConversionRate(GhostfolioSidekick.Model.Currency,GhostfolioSidekick.Model.Currency,System.DateTime)~System.Threading.Tasks.Task{System.Decimal}")]
