// <auto-generated />
using System;
using GhostfolioSidekick.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GhostfolioSidekick.Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("GhostfolioSidekick.Model.Accounts.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlatformId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlatformId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Accounts.Balance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Balances", (string)null);
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Accounts.Platform", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Platforms");
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Activities.Activity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("HoldingId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SortingPriority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransactionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("HoldingId");

                    b.ToTable("Activities", (string)null);

                    b.HasDiscriminator<string>("Type").HasValue("Activity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Activities.Holding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Holdings", (string)null);
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Symbols.CountryWeight", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Continent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SymbolProfileSymbol")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Weight")
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.HasIndex("SymbolProfileSymbol");

                    b.ToTable("CountryWeights", (string)null);
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Symbols.SectorWeight", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("SymbolProfileSymbol")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Weight")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.HasIndex("SymbolProfileSymbol");

                    b.ToTable("SectorWeights", (string)null);
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Symbols.SymbolProfile", b =>
                {
                    b.Property<string>("Symbol")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetSubClass")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ISIN")
                        .HasColumnType("TEXT");

                    b.Property<string>("Identifiers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Symbol");

                    b.ToTable("SymbolProfiles", (string)null);
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Activities.Types.BuySellActivity", b =>
                {
                    b.HasBaseType("GhostfolioSidekick.Model.Activities.Activity");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("1");
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Activities.Types.CashDepositWithdrawalActivity", b =>
                {
                    b.HasBaseType("GhostfolioSidekick.Model.Activities.Activity");

                    b.HasDiscriminator().HasValue("2");
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Accounts.Account", b =>
                {
                    b.HasOne("GhostfolioSidekick.Model.Accounts.Platform", "Platform")
                        .WithMany()
                        .HasForeignKey("PlatformId");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Accounts.Balance", b =>
                {
                    b.HasOne("GhostfolioSidekick.Model.Accounts.Account", null)
                        .WithMany("Balance")
                        .HasForeignKey("AccountId");

                    b.OwnsOne("GhostfolioSidekick.Model.Money", "Money", b1 =>
                        {
                            b1.Property<int>("BalanceId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT")
                                .HasColumnName("Amount");

                            b1.HasKey("BalanceId");

                            b1.ToTable("Balances");

                            b1.WithOwner()
                                .HasForeignKey("BalanceId");

                            b1.OwnsOne("GhostfolioSidekick.Model.Currency", "Currency", b2 =>
                                {
                                    b2.Property<int>("MoneyBalanceId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Symbol")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("Currency");

                                    b2.HasKey("MoneyBalanceId");

                                    b2.ToTable("Balances");

                                    b2.WithOwner()
                                        .HasForeignKey("MoneyBalanceId");
                                });

                            b1.Navigation("Currency")
                                .IsRequired();
                        });

                    b.Navigation("Money")
                        .IsRequired();
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Activities.Activity", b =>
                {
                    b.HasOne("GhostfolioSidekick.Model.Accounts.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GhostfolioSidekick.Model.Activities.Holding", null)
                        .WithMany("Activities")
                        .HasForeignKey("HoldingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Symbols.CountryWeight", b =>
                {
                    b.HasOne("GhostfolioSidekick.Model.Symbols.SymbolProfile", null)
                        .WithMany("CountryWeight")
                        .HasForeignKey("SymbolProfileSymbol");
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Symbols.SectorWeight", b =>
                {
                    b.HasOne("GhostfolioSidekick.Model.Symbols.SymbolProfile", null)
                        .WithMany("SectorWeights")
                        .HasForeignKey("SymbolProfileSymbol");
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Symbols.SymbolProfile", b =>
                {
                    b.OwnsOne("GhostfolioSidekick.Model.Currency", "Currency", b1 =>
                        {
                            b1.Property<string>("SymbolProfileSymbol")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Symbol")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Currency");

                            b1.HasKey("SymbolProfileSymbol");

                            b1.ToTable("SymbolProfiles");

                            b1.WithOwner()
                                .HasForeignKey("SymbolProfileSymbol");
                        });

                    b.Navigation("Currency")
                        .IsRequired();
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Activities.Types.BuySellActivity", b =>
                {
                    b.OwnsMany("GhostfolioSidekick.Model.Money", "Fees", b1 =>
                        {
                            b1.Property<string>("BuySellActivityId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT")
                                .HasColumnName("Amount");

                            b1.HasKey("BuySellActivityId", "Id");

                            b1.ToTable("Activities_Fees");

                            b1.WithOwner()
                                .HasForeignKey("BuySellActivityId");

                            b1.OwnsOne("GhostfolioSidekick.Model.Currency", "Currency", b2 =>
                                {
                                    b2.Property<string>("MoneyBuySellActivityId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("MoneyId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Symbol")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("Currency");

                                    b2.HasKey("MoneyBuySellActivityId", "MoneyId");

                                    b2.ToTable("Activities_Fees");

                                    b2.WithOwner()
                                        .HasForeignKey("MoneyBuySellActivityId", "MoneyId");
                                });

                            b1.Navigation("Currency")
                                .IsRequired();
                        });

                    b.OwnsMany("GhostfolioSidekick.Model.Money", "Taxes", b1 =>
                        {
                            b1.Property<string>("BuySellActivityId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT")
                                .HasColumnName("Amount");

                            b1.HasKey("BuySellActivityId", "Id");

                            b1.ToTable("Activities_Taxes");

                            b1.WithOwner()
                                .HasForeignKey("BuySellActivityId");

                            b1.OwnsOne("GhostfolioSidekick.Model.Currency", "Currency", b2 =>
                                {
                                    b2.Property<string>("MoneyBuySellActivityId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("MoneyId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Symbol")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("Currency");

                                    b2.HasKey("MoneyBuySellActivityId", "MoneyId");

                                    b2.ToTable("Activities_Taxes");

                                    b2.WithOwner()
                                        .HasForeignKey("MoneyBuySellActivityId", "MoneyId");
                                });

                            b1.Navigation("Currency")
                                .IsRequired();
                        });

                    b.OwnsOne("GhostfolioSidekick.Model.Money", "UnitPrice", b1 =>
                        {
                            b1.Property<string>("BuySellActivityId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("TEXT")
                                .HasColumnName("Amount");

                            b1.HasKey("BuySellActivityId");

                            b1.ToTable("Activities");

                            b1.WithOwner()
                                .HasForeignKey("BuySellActivityId");

                            b1.OwnsOne("GhostfolioSidekick.Model.Currency", "Currency", b2 =>
                                {
                                    b2.Property<string>("MoneyBuySellActivityId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Symbol")
                                        .IsRequired()
                                        .ValueGeneratedOnUpdateSometimes()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("Currency");

                                    b2.HasKey("MoneyBuySellActivityId");

                                    b2.ToTable("Activities");

                                    b2.WithOwner()
                                        .HasForeignKey("MoneyBuySellActivityId");
                                });

                            b1.Navigation("Currency")
                                .IsRequired();
                        });

                    b.Navigation("Fees");

                    b.Navigation("Taxes");

                    b.Navigation("UnitPrice");
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Activities.Types.CashDepositWithdrawalActivity", b =>
                {
                    b.OwnsOne("GhostfolioSidekick.Model.Money", "Amount", b1 =>
                        {
                            b1.Property<string>("CashDepositWithdrawalActivityId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("TEXT")
                                .HasColumnName("Amount");

                            b1.HasKey("CashDepositWithdrawalActivityId");

                            b1.ToTable("Activities");

                            b1.WithOwner()
                                .HasForeignKey("CashDepositWithdrawalActivityId");

                            b1.OwnsOne("GhostfolioSidekick.Model.Currency", "Currency", b2 =>
                                {
                                    b2.Property<string>("MoneyCashDepositWithdrawalActivityId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Symbol")
                                        .IsRequired()
                                        .ValueGeneratedOnUpdateSometimes()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("Currency");

                                    b2.HasKey("MoneyCashDepositWithdrawalActivityId");

                                    b2.ToTable("Activities");

                                    b2.WithOwner()
                                        .HasForeignKey("MoneyCashDepositWithdrawalActivityId");
                                });

                            b1.Navigation("Currency")
                                .IsRequired();
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Accounts.Account", b =>
                {
                    b.Navigation("Balance");
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Activities.Holding", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Symbols.SymbolProfile", b =>
                {
                    b.Navigation("CountryWeight");

                    b.Navigation("SectorWeights");
                });
#pragma warning restore 612, 618
        }
    }
}
