// <auto-generated />
using System;
using System.Collections.Generic;
using GhostfolioSidekick.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GhostfolioSidekick.Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("GhostfolioSidekick.Database.TypeConfigurations.PartialSymbolIdentifierActivity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ActivityId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("PartialSymbolIdentifierId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("PartialSymbolIdentifierId");

                    b.ToTable("PartialSymbolIdentifierActivity");
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Accounts.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlatformId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SyncActivities")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("SyncBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("PlatformId");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Accounts.Balance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Money", "GhostfolioSidekick.Model.Accounts.Balance.Money#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT")
                                .HasColumnName("Amount");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Currency", "GhostfolioSidekick.Model.Accounts.Balance.Money#Money.Currency#Currency", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Symbol")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("Currency");
                                });
                        });

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "Date")
                        .IsUnique();

                    b.ToTable("Balances", (string)null);
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Accounts.Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Platforms");
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Activities.Activity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("TEXT");

                    b.Property<int?>("HoldingId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SortingPriority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("Date");

                    b.HasIndex("HoldingId");

                    b.ToTable("Activities", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("Activity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Activities.CalculatedPriceTrace", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Key", 0);

                    b.Property<long>("ActivityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "NewPrice", "GhostfolioSidekick.Model.Activities.CalculatedPriceTrace.NewPrice#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT")
                                .HasColumnName("NewPrice");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Currency", "GhostfolioSidekick.Model.Activities.CalculatedPriceTrace.NewPrice#Money.Currency#Currency", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Symbol")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("CurrencyNewPrice");
                                });
                        });

                    b.HasKey("ID");

                    b.HasIndex("ActivityId");

                    b.ToTable("CalculatedPriceTrace", (string)null);
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Activities.PartialSymbolIdentifier", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Key", 0);

                    b.Property<string>("AllowedAssetClasses")
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedAssetSubClasses")
                        .HasColumnType("TEXT");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("Identifier", "AllowedAssetClasses", "AllowedAssetSubClasses")
                        .IsUnique()
                        .HasDatabaseName("IX_PartialSymbolIdentifiers_Identifier_AllowedAssetClass_AllowedAssetSubClass");

                    b.ToTable("PartialSymbolIdentifiers", (string)null);
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Activities.Types.MoneyLists.BuyActivityFee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ActivityId")
                        .HasColumnType("INTEGER");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Money", "GhostfolioSidekick.Model.Activities.Types.MoneyLists.BuyActivityFee.Money#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT")
                                .HasColumnName("Money");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Currency", "GhostfolioSidekick.Model.Activities.Types.MoneyLists.BuyActivityFee.Money#Money.Currency#Currency", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Symbol")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("CurrencyMoney");
                                });
                        });

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.ToTable("BuyActivityFees", (string)null);
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Activities.Types.MoneyLists.BuyActivityTax", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ActivityId")
                        .HasColumnType("INTEGER");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Money", "GhostfolioSidekick.Model.Activities.Types.MoneyLists.BuyActivityTax.Money#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT")
                                .HasColumnName("Money");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Currency", "GhostfolioSidekick.Model.Activities.Types.MoneyLists.BuyActivityTax.Money#Money.Currency#Currency", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Symbol")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("CurrencyMoney");
                                });
                        });

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.ToTable("BuyActivityTaxes", (string)null);
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Activities.Types.MoneyLists.DividendActivityFee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ActivityId")
                        .HasColumnType("INTEGER");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Money", "GhostfolioSidekick.Model.Activities.Types.MoneyLists.DividendActivityFee.Money#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT")
                                .HasColumnName("Money");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Currency", "GhostfolioSidekick.Model.Activities.Types.MoneyLists.DividendActivityFee.Money#Money.Currency#Currency", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Symbol")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("CurrencyMoney");
                                });
                        });

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.ToTable("DividendActivityFees", (string)null);
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Activities.Types.MoneyLists.DividendActivityTax", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ActivityId")
                        .HasColumnType("INTEGER");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Money", "GhostfolioSidekick.Model.Activities.Types.MoneyLists.DividendActivityTax.Money#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT")
                                .HasColumnName("Money");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Currency", "GhostfolioSidekick.Model.Activities.Types.MoneyLists.DividendActivityTax.Money#Money.Currency#Currency", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Symbol")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("CurrencyMoney");
                                });
                        });

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.ToTable("DividendActivityTaxes", (string)null);
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Activities.Types.MoneyLists.ReceiveActivityFee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ActivityId")
                        .HasColumnType("INTEGER");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Money", "GhostfolioSidekick.Model.Activities.Types.MoneyLists.ReceiveActivityFee.Money#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT")
                                .HasColumnName("Money");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Currency", "GhostfolioSidekick.Model.Activities.Types.MoneyLists.ReceiveActivityFee.Money#Money.Currency#Currency", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Symbol")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("CurrencyMoney");
                                });
                        });

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.ToTable("ReceiveActivityFees", (string)null);
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Activities.Types.MoneyLists.SellActivityFee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ActivityId")
                        .HasColumnType("INTEGER");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Money", "GhostfolioSidekick.Model.Activities.Types.MoneyLists.SellActivityFee.Money#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT")
                                .HasColumnName("Money");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Currency", "GhostfolioSidekick.Model.Activities.Types.MoneyLists.SellActivityFee.Money#Money.Currency#Currency", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Symbol")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("CurrencyMoney");
                                });
                        });

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.ToTable("SellActivityFees", (string)null);
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Activities.Types.MoneyLists.SellActivityTax", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ActivityId")
                        .HasColumnType("INTEGER");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Money", "GhostfolioSidekick.Model.Activities.Types.MoneyLists.SellActivityTax.Money#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT")
                                .HasColumnName("Money");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Currency", "GhostfolioSidekick.Model.Activities.Types.MoneyLists.SellActivityTax.Money#Money.Currency#Currency", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Symbol")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("CurrencyMoney");
                                });
                        });

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.ToTable("SellActivityTaxes", (string)null);
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Activities.Types.MoneyLists.SendActivityFee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ActivityId")
                        .HasColumnType("INTEGER");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Money", "GhostfolioSidekick.Model.Activities.Types.MoneyLists.SendActivityFee.Money#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT")
                                .HasColumnName("Money");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Currency", "GhostfolioSidekick.Model.Activities.Types.MoneyLists.SendActivityFee.Money#Money.Currency#Currency", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Symbol")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("CurrencyMoney");
                                });
                        });

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.ToTable("SendActivityFees", (string)null);
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Holding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PartialSymbolIdentifiers")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("PartialSymbolIdentifiers");

                    b.HasKey("Id");

                    b.ToTable("Holdings", (string)null);
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Market.CurrencyExchangeRate", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Key", 0);

                    b.Property<decimal>("Close")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CurrencyExchangeProfileID")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("High")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Low")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Open")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TradingVolume")
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Currency", "GhostfolioSidekick.Model.Market.CurrencyExchangeRate.Currency#Currency", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Symbol")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Currency");
                        });

                    b.HasKey("ID");

                    b.HasIndex("CurrencyExchangeProfileID", "Date")
                        .IsUnique()
                        .HasDatabaseName("IX_CurrencyExchangeRate_CurrencyExchangeProfileID_Date");

                    b.ToTable("CurrencyExchangeRate", (string)null);
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Market.Dividend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DividendState")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DividendType")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("ExDividendDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SymbolProfileDataSource")
                        .HasColumnType("TEXT");

                    b.Property<string>("SymbolProfileSymbol")
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Amount", "GhostfolioSidekick.Model.Market.Dividend.Amount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT")
                                .HasColumnName("Amount");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Currency", "GhostfolioSidekick.Model.Market.Dividend.Amount#Money.Currency#Currency", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Symbol")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("CurrencyAmount");
                                });
                        });

                    b.HasKey("Id");

                    b.HasIndex("SymbolProfileSymbol", "SymbolProfileDataSource");

                    b.ToTable("Dividends");
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Market.MarketData", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Key", 0);

                    b.Property<decimal>("Close")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("Date");

                    b.Property<decimal>("High")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsGenerated")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Low")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Open")
                        .HasColumnType("TEXT");

                    b.Property<string>("SymbolProfileDataSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SymbolProfileSymbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TradingVolume")
                        .HasColumnType("TEXT")
                        .HasColumnName("TradingVolume");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Currency", "GhostfolioSidekick.Model.Market.MarketData.Currency#Currency", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Symbol")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Currency");
                        });

                    b.HasKey("ID");

                    b.HasIndex("SymbolProfileSymbol", "SymbolProfileDataSource");

                    b.HasIndex("SymbolProfileDataSource", "SymbolProfileSymbol", "Date")
                        .IsUnique()
                        .HasDatabaseName("IX_MarketData_SymbolProfileDataSource_SymbolProfileSymbol_Date");

                    b.ToTable("MarketData", (string)null);
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Market.StockSplit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Key", 0);

                    b.Property<decimal>("AfterSplit")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BeforeSplit")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("SymbolProfileDataSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SymbolProfileSymbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("SymbolProfileSymbol", "SymbolProfileDataSource");

                    b.ToTable("StockSplits", (string)null);
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Performance.CalculatedSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AverageCostPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentUnitPrice")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("HoldingId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalInvested")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalValue")
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Currency", "GhostfolioSidekick.Model.Performance.CalculatedSnapshot.Currency#Currency", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Symbol")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Currency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("AccountId", "Date");

                    b.HasIndex("HoldingId", "Date");

                    b.HasIndex("HoldingId", "AccountId", "Date")
                        .IsUnique();

                    b.ToTable("CalculatedSnapshots", (string)null);
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Symbols.CurrencyExchangeProfile", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceCurrency")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("SourceCurrency");

                    b.Property<string>("TargetCurrency")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("TargetCurrency");

                    b.HasKey("ID");

                    b.HasIndex("SourceCurrency", "TargetCurrency")
                        .IsUnique();

                    b.ToTable("CurrencyExchangeProfile", (string)null);
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Symbols.SymbolProfile", b =>
                {
                    b.Property<string>("Symbol")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSource")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetSubClass")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryWeight")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("HoldingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ISIN")
                        .HasColumnType("TEXT");

                    b.Property<string>("Identifiers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("SectorWeights")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Currency", "GhostfolioSidekick.Model.Symbols.SymbolProfile.Currency#Currency", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Symbol")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Currency");
                        });

                    b.HasKey("Symbol", "DataSource");

                    b.HasIndex("HoldingId");

                    b.ToTable("SymbolProfiles", (string)null);
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Tasks.TaskRun", b =>
                {
                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<bool>("InProgress")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastException")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastUpdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("NextSchedule")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Scheduled")
                        .HasColumnType("INTEGER");

                    b.HasKey("Type");

                    b.ToTable("TaskRuns", (string)null);
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Tasks.TaskRunLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskRunType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TaskRunType");

                    b.ToTable("TaskRunLogs", (string)null);
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Activities.ActivityWithAmount", b =>
                {
                    b.HasBaseType("GhostfolioSidekick.Model.Activities.Activity");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Amount", "GhostfolioSidekick.Model.Activities.ActivityWithAmount.Amount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT")
                                .HasColumnName("Amount");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Currency", "GhostfolioSidekick.Model.Activities.ActivityWithAmount.Amount#Money.Currency#Currency", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Symbol")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("CurrencyAmount");
                                });
                        });

                    b.HasDiscriminator().HasValue("ActivityWithAmount");
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Activities.ActivityWithQuantityAndUnitPrice", b =>
                {
                    b.HasBaseType("GhostfolioSidekick.Model.Activities.Activity");

                    b.Property<decimal>("AdjustedQuantity")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "AdjustedUnitPrice", "GhostfolioSidekick.Model.Activities.ActivityWithQuantityAndUnitPrice.AdjustedUnitPrice#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT")
                                .HasColumnName("AdjustedUnitPrice");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Currency", "GhostfolioSidekick.Model.Activities.ActivityWithQuantityAndUnitPrice.AdjustedUnitPrice#Money.Currency#Currency", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Symbol")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("CurrencyAdjustedUnitPrice");
                                });
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TotalTransactionAmount", "GhostfolioSidekick.Model.Activities.ActivityWithQuantityAndUnitPrice.TotalTransactionAmount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT")
                                .HasColumnName("TotalTransactionAmount");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Currency", "GhostfolioSidekick.Model.Activities.ActivityWithQuantityAndUnitPrice.TotalTransactionAmount#Money.Currency#Currency", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Symbol")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("CurrencyTotalTransactionAmount");
                                });
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "UnitPrice", "GhostfolioSidekick.Model.Activities.ActivityWithQuantityAndUnitPrice.UnitPrice#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT")
                                .HasColumnName("UnitPrice");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Currency", "GhostfolioSidekick.Model.Activities.ActivityWithQuantityAndUnitPrice.UnitPrice#Money.Currency#Currency", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Symbol")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("CurrencyUnitPrice");
                                });
                        });

                    b.HasDiscriminator().HasValue("ActivityWithQuantityAndUnitPrice");
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Activities.Types.CashDepositActivity", b =>
                {
                    b.HasBaseType("GhostfolioSidekick.Model.Activities.ActivityWithAmount");

                    b.HasDiscriminator().HasValue("CashDeposit");
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Activities.Types.CashWithdrawalActivity", b =>
                {
                    b.HasBaseType("GhostfolioSidekick.Model.Activities.ActivityWithAmount");

                    b.HasDiscriminator().HasValue("CashWithdrawal");
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Activities.Types.DividendActivity", b =>
                {
                    b.HasBaseType("GhostfolioSidekick.Model.Activities.ActivityWithAmount");

                    b.HasDiscriminator().HasValue("Dividend");
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Activities.Types.FeeActivity", b =>
                {
                    b.HasBaseType("GhostfolioSidekick.Model.Activities.ActivityWithAmount");

                    b.HasDiscriminator().HasValue("Fee");
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Activities.Types.GiftFiatActivity", b =>
                {
                    b.HasBaseType("GhostfolioSidekick.Model.Activities.ActivityWithAmount");

                    b.HasDiscriminator().HasValue("GiftFiat");
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Activities.Types.InterestActivity", b =>
                {
                    b.HasBaseType("GhostfolioSidekick.Model.Activities.ActivityWithAmount");

                    b.HasDiscriminator().HasValue("Interest");
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Activities.Types.KnownBalanceActivity", b =>
                {
                    b.HasBaseType("GhostfolioSidekick.Model.Activities.ActivityWithAmount");

                    b.HasDiscriminator().HasValue("KnownBalance");
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Activities.Types.LiabilityActivity", b =>
                {
                    b.HasBaseType("GhostfolioSidekick.Model.Activities.ActivityWithAmount");

                    b.HasDiscriminator().HasValue("Liability");
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Activities.Types.RepayBondActivity", b =>
                {
                    b.HasBaseType("GhostfolioSidekick.Model.Activities.ActivityWithAmount");

                    b.HasDiscriminator().HasValue("RepayBond");
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Activities.Types.ValuableActivity", b =>
                {
                    b.HasBaseType("GhostfolioSidekick.Model.Activities.ActivityWithAmount");

                    b.HasDiscriminator().HasValue("Valuable");
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Activities.Types.BuyActivity", b =>
                {
                    b.HasBaseType("GhostfolioSidekick.Model.Activities.ActivityWithQuantityAndUnitPrice");

                    b.HasDiscriminator().HasValue("Buy");
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Activities.Types.GiftAssetActivity", b =>
                {
                    b.HasBaseType("GhostfolioSidekick.Model.Activities.ActivityWithQuantityAndUnitPrice");

                    b.HasDiscriminator().HasValue("GiftAsset");
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Activities.Types.ReceiveActivity", b =>
                {
                    b.HasBaseType("GhostfolioSidekick.Model.Activities.ActivityWithQuantityAndUnitPrice");

                    b.HasDiscriminator().HasValue("Receive");
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Activities.Types.SellActivity", b =>
                {
                    b.HasBaseType("GhostfolioSidekick.Model.Activities.ActivityWithQuantityAndUnitPrice");

                    b.HasDiscriminator().HasValue("Sell");
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Activities.Types.SendActivity", b =>
                {
                    b.HasBaseType("GhostfolioSidekick.Model.Activities.ActivityWithQuantityAndUnitPrice");

                    b.HasDiscriminator().HasValue("Send");
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Activities.Types.StakingRewardActivity", b =>
                {
                    b.HasBaseType("GhostfolioSidekick.Model.Activities.ActivityWithQuantityAndUnitPrice");

                    b.HasDiscriminator().HasValue("StakingReward");
                });

            modelBuilder.Entity("GhostfolioSidekick.Database.TypeConfigurations.PartialSymbolIdentifierActivity", b =>
                {
                    b.HasOne("GhostfolioSidekick.Model.Activities.ActivityWithQuantityAndUnitPrice", null)
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GhostfolioSidekick.Model.Activities.Types.DividendActivity", null)
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GhostfolioSidekick.Model.Activities.Types.LiabilityActivity", null)
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GhostfolioSidekick.Model.Activities.Types.RepayBondActivity", null)
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GhostfolioSidekick.Model.Activities.Types.ValuableActivity", null)
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GhostfolioSidekick.Model.Activities.PartialSymbolIdentifier", null)
                        .WithMany()
                        .HasForeignKey("PartialSymbolIdentifierId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Accounts.Account", b =>
                {
                    b.HasOne("GhostfolioSidekick.Model.Accounts.Platform", "Platform")
                        .WithMany()
                        .HasForeignKey("PlatformId");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Accounts.Balance", b =>
                {
                    b.HasOne("GhostfolioSidekick.Model.Accounts.Account", null)
                        .WithMany("Balance")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Activities.Activity", b =>
                {
                    b.HasOne("GhostfolioSidekick.Model.Accounts.Account", "Account")
                        .WithMany("Activities")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GhostfolioSidekick.Model.Holding", "Holding")
                        .WithMany("Activities")
                        .HasForeignKey("HoldingId");

                    b.Navigation("Account");

                    b.Navigation("Holding");
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Activities.CalculatedPriceTrace", b =>
                {
                    b.HasOne("GhostfolioSidekick.Model.Activities.ActivityWithQuantityAndUnitPrice", null)
                        .WithMany("AdjustedUnitPriceSource")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Activities.Types.MoneyLists.BuyActivityFee", b =>
                {
                    b.HasOne("GhostfolioSidekick.Model.Activities.Types.BuyActivity", null)
                        .WithMany("Fees")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Activities.Types.MoneyLists.BuyActivityTax", b =>
                {
                    b.HasOne("GhostfolioSidekick.Model.Activities.Types.BuyActivity", null)
                        .WithMany("Taxes")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Activities.Types.MoneyLists.DividendActivityFee", b =>
                {
                    b.HasOne("GhostfolioSidekick.Model.Activities.Types.DividendActivity", null)
                        .WithMany("Fees")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Activities.Types.MoneyLists.DividendActivityTax", b =>
                {
                    b.HasOne("GhostfolioSidekick.Model.Activities.Types.DividendActivity", null)
                        .WithMany("Taxes")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Activities.Types.MoneyLists.ReceiveActivityFee", b =>
                {
                    b.HasOne("GhostfolioSidekick.Model.Activities.Types.ReceiveActivity", null)
                        .WithMany("Fees")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Activities.Types.MoneyLists.SellActivityFee", b =>
                {
                    b.HasOne("GhostfolioSidekick.Model.Activities.Types.SellActivity", null)
                        .WithMany("Fees")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Activities.Types.MoneyLists.SellActivityTax", b =>
                {
                    b.HasOne("GhostfolioSidekick.Model.Activities.Types.SellActivity", null)
                        .WithMany("Taxes")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Activities.Types.MoneyLists.SendActivityFee", b =>
                {
                    b.HasOne("GhostfolioSidekick.Model.Activities.Types.SendActivity", null)
                        .WithMany("Fees")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Market.CurrencyExchangeRate", b =>
                {
                    b.HasOne("GhostfolioSidekick.Model.Symbols.CurrencyExchangeProfile", null)
                        .WithMany("Rates")
                        .HasForeignKey("CurrencyExchangeProfileID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Market.Dividend", b =>
                {
                    b.HasOne("GhostfolioSidekick.Model.Symbols.SymbolProfile", null)
                        .WithMany("Dividends")
                        .HasForeignKey("SymbolProfileSymbol", "SymbolProfileDataSource");
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Market.MarketData", b =>
                {
                    b.HasOne("GhostfolioSidekick.Model.Symbols.SymbolProfile", null)
                        .WithMany("MarketData")
                        .HasForeignKey("SymbolProfileSymbol", "SymbolProfileDataSource")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Market.StockSplit", b =>
                {
                    b.HasOne("GhostfolioSidekick.Model.Symbols.SymbolProfile", null)
                        .WithMany("StockSplits")
                        .HasForeignKey("SymbolProfileSymbol", "SymbolProfileDataSource")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Performance.CalculatedSnapshot", b =>
                {
                    b.HasOne("GhostfolioSidekick.Model.Holding", "Holding")
                        .WithMany("CalculatedSnapshots")
                        .HasForeignKey("HoldingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Holding");
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Symbols.SymbolProfile", b =>
                {
                    b.HasOne("GhostfolioSidekick.Model.Holding", null)
                        .WithMany("SymbolProfiles")
                        .HasForeignKey("HoldingId");
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Tasks.TaskRunLog", b =>
                {
                    b.HasOne("GhostfolioSidekick.Model.Tasks.TaskRun", "TaskRun")
                        .WithMany("Logs")
                        .HasForeignKey("TaskRunType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskRun");
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Accounts.Account", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Balance");
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Holding", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("CalculatedSnapshots");

                    b.Navigation("SymbolProfiles");
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Symbols.CurrencyExchangeProfile", b =>
                {
                    b.Navigation("Rates");
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Symbols.SymbolProfile", b =>
                {
                    b.Navigation("Dividends");

                    b.Navigation("MarketData");

                    b.Navigation("StockSplits");
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Tasks.TaskRun", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Activities.ActivityWithQuantityAndUnitPrice", b =>
                {
                    b.Navigation("AdjustedUnitPriceSource");
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Activities.Types.DividendActivity", b =>
                {
                    b.Navigation("Fees");

                    b.Navigation("Taxes");
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Activities.Types.BuyActivity", b =>
                {
                    b.Navigation("Fees");

                    b.Navigation("Taxes");
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Activities.Types.ReceiveActivity", b =>
                {
                    b.Navigation("Fees");
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Activities.Types.SellActivity", b =>
                {
                    b.Navigation("Fees");

                    b.Navigation("Taxes");
                });

            modelBuilder.Entity("GhostfolioSidekick.Model.Activities.Types.SendActivity", b =>
                {
                    b.Navigation("Fees");
                });
#pragma warning restore 612, 618
        }
    }
}
