<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AssemblyName>GhostfolioSidekick.$(MSBuildProjectName)</AssemblyName>
		<RootNamespace>GhostfolioSidekick.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\Database\Database.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Benchmarks\" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
	  <PackageReference Include="Microsoft.Extensions.AI.Abstractions" />
	  <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
	</ItemGroup>

</Project>
